export enum RevokedReason {
  USER_LOGOUT = "USER_LOGOUT",
  EXPIRED = "EXPIRED",
  ADMIN_REVOKED = "ADMIN_REVOKED",
  PASSWORD_CHANGE = "PASSWORD_CHANGE",
  TOKEN_REUSE_DETECTED = "TOKEN_REUSE_DETECTED",
  ROTATED = "ROTATED",
  OTHER = "OTHER",
}
